server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 10m
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    driver-class-name:  net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/pi99ydb?characterEncoding=utf8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/shopdb?characterEncoding=utf8&serverTimezone=Asia/Seoul
    #user01/111111
    username: pi99y
    password: 123123
mybatis:
  type-aliases-package: com.hana.app.data.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
app:
  kakao:
    client-id: 6010fcb18c95b478809e9791063221af
    client-secret: C3G32lHm9Zlw4ZXRQpkPfAS1MJ41bwej
    redirect-url: http://localhost:8080/kakao/access

